### ISSUE TITLE
multicontas coloca para trabalhar apenas na primeira conta

### ISSUE THREAD

**Issue by Jh0nyB** [carecabrilhante/BombBot#1]
Bom dia, o multicontas depois que coloca a primeira conta ele vai para a segunda e entra direto no mapa em vez de ir no botão heroes, sei que está em beta mas queria deixar o comentário sobre isso para ajudar com o desenvolvimento, o bot está ficando cada vez melhor, offset do login por usuário e senha as vezes clica fora do botão também, mas como ele atualiza a página não interfere em muita coisa, estou usando no windows

**Comment by USPaiva** [comment]
> Bom dia, o multicontas depois que coloca a primeira conta ele vai para a segunda e entra direto no mapa em vez de ir no botão heroes, sei que está em beta mas queria deixar o comentário sobre isso para ajudar com o desenvolvimento, o bot está ficando cada vez melhor, offset do login por usuário e senha as vezes clica fora do botão também, mas como ele atualiza a página não interfere em muita coisa, estou usando no windows

acabei de fazer certas correções no bot. e obrigado pelo feedback :)
